export * from './BadRequestPage/BadRequestPage';
export * from './DetailsPages/index';
export * from './DiscoverPages/index';
export * from './HomePage/HomePage';
export * from './AuthPages/index';
export * from './MovieAndTvPages/index';
export * from './NotFoundPage/NotFoundPage';
export * from './PersonDetailsPage/PersonDetailsPage';
export * from './PopularPersonPage/PopularPersonPage';